queries = [
    # General and Popular Keywords
    "Hindi Bollywood Hits",
    "Top Bollywood Songs",
    "Popular Hindi Songs",
    "Classic Hindi Songs",
    "Latest Hindi Songs",
    "Bollywood Music Playlist",
    "Top Hindi Tracks",
    "Hit Hindi Songs",
    "Hindi Movie Songs",
    "Hindi Love Songs",
    "90s Bollywood Songs",
    "80s Hindi Songs",
    "70s Hindi Classics",
    "Early 2000s Bollywood Hits",
    "Vintage Hindi Songs",
    "Romantic Hindi Songs",
    "Dance Hindi Songs",
    "Sad Hindi Songs",
    "Party Hindi Songs",
    "Melancholic Hindi Music",
    "Bollywood Romantic Ballads",
    "Hindi Rock Songs",
    "Hindi Folk Songs",
    "Bollywood Love Songs",
    "Songs by Lata Mangeshkar",
    "Songs by Kishore Kumar",
    "A.R. Rahman Hits",
    "Songs by Arijit Singh",
    "Bollywood Songs by Shreya Ghoshal",
    "Hindi Festival Songs (e.g., Diwali, Holi)",
    "Hindi Inspirational Songs",
    "Patriotic Hindi Songs",
    "Hindi Wedding Songs",
    "Bollywood Top 50",
    "Hindi Music for Relaxation",
    "Bollywood Essentials",
    "Hindi Hits of the Year",
    "Punjabi Bollywood Songs",
    "South Indian Hindi Songs",
    "Hindi Songs from Mumbai",
    "Hindi Bollywood 90s Hits",
    "Top Romantic Hindi Songs of 2023",
    "Dance Hits Bollywood Playlist",
    "Popular Hindi Songs by Arijit Singh",
    "Classic 80s Bollywood Music"
]
